// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repository

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteProduct(ctx context.Context, id int64) error
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetProductList(ctx context.Context, arg GetProductListParams) ([]Product, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetUser(ctx context.Context, phoneNumber string) (User, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
}

var _ Querier = (*Queries)(nil)
